version: '3'
services:
  infer:
    image: david712/infer:1.1.0
    container_name: infer
    build:
      context: ./infer_code
      dockerfile: Dockerfile
    volumes:
      - ./infer_code:/app/infer_code
    # keep the container running
    command: tail -f /dev/null
  
  klee:
    image: klee/klee:3.0
    container_name: klee
    volumes:
      - ./klee_code:/app/klee_code
    # keep the container running
    command: tail -f /dev/null
