

services:

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

    # If you want to use GPU, uncomment the following lines
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  infer:
    image: david712/infer:latest
    container_name: infer
    build:
      context: ./infer_code
      dockerfile: Dockerfile
    working_dir: /app/pipeline
    volumes:
      - ./pipeline:/app/pipeline
      - ./leetcode-master:/app/leetcode-master
    command: tail -f /dev/null
  

volumes:
      ollama:
  